### ISSUE TITLE
关于请求报错的问题

### ISSUE THREAD

**Issue by formattedzzz** [ngu2008/wanandroid#1]
我也是根据flutter中文网的介绍在学习flutter  在请求的时候老是报错 不知道是啥原因，如下
E/flutter (18841): [ERROR:flutter/shell/common/shell.cc(188)] Dart Error: Unhandled exception:
E/flutter (18841): DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'www.baidu.com' (OS Error: No address associated with hostname, errno = 7)
flutter 自代的dart:io 也是这样 编译没问题。不知道大佬有没有遇到过

**Comment by ngu2008** [comment]
看一下你发送请求的代码

**Comment by formattedzzz** [comment]
```dart
void httpget() async {
    try {
      print('1');
      Response response = await Dio().get("https://www.baidu.com");
      print('2');
      print(response);
    } catch (e) {
      print(e);
    }
  }
```
就dio那个库最简单的用法，调了下自己的线上接口也没用

**Comment by ngu2008** [comment]
我试了一下，跟代码没关系，应该是你的环境有问题
![qq 20190307095445](https://user-images.githubusercontent.com/19800003/53926639-3003d700-40bf-11e9-8ab4-bd9802e4eedb.jpg)

**Comment by ngu2008** [comment]
关闭
